### ISSUE TITLE
Wishlist: Expand @ user ping to general tagging

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/PulseMonitor#7]
Currently, the `notify` command allows you to add a ping for any regex match in the Halflife output. I am using it to get an inbox notification when certain events happen ... but it's kind of cumbersome when some of those events are really frequent. It would improve usability if the facility could be used to add a simple unique tag to all occurrences, so that we can use the (very crude) chat search to find all recent occurrences of a particular regex, but not spam our inboxes.

I'm thinking it should not be hard to refactor the notification support to do this instead, and then perhaps reimplement @ user ping notifications using this more general tagging mechanism.

**Comment by double-fault** [comment]
Shouldn't be too difficult. A very messy but working method would be store all Halflife messages; if we don't want to do that, we can store reports which match certain regexes. Then, if I want to view specific reports, I can run a command like `latest <regex here> <number of report>`, and then it'll show the latest reports matching the regex entered.

**Comment by tripleee** [comment]
Here's an example of what my pings look like at the moment:
https://chat.stackexchange.com/search?q=%40tripleee&user=295223&room=65945

**Comment by tripleee** [comment]
... you'll notice that the search is slightly inexact; it actually finds "tripleee" anywhere (including in the URL in the restart message). Finding a good unique format for the tags is an important consideration here, though not properly part of the Python development task.
