### ISSUE TITLE
Update to the latest commit

### ISSUE THREAD

**Issue by double-fault** [Charcoal-SE/PulseMonitor#8]
You need to update to the latest Botpy version to sync with Redunda. Here's what you need to do:

1. Go [here](https://redunda.sobotics.org/bots/27/bot_instances) and choose "Create New". Enter the details for your instance and create the new instance. Copy the instance key to your clipboard.
2. Make a new file `redunda_key.txt` at `~/.pulsemonitor`. Paste your key here (nothing else but the key).
3. Update the Docker image by pulling the latest code, and everything should work!

**Comment by double-fault** [comment]
Also, your instance key is supposed to be private; I don't know if the Redunda page mentions it, but please don't share your key with anyone!

**Comment by tripleee** [comment]
Added a missed dependency and the Redunda key. Thanks!

**Comment by double-fault** [comment]
@tripleee the bot doesn’t seem alive on redunda. Are you sure you have set it up properly? What do the logs show?
