### ISSUE TITLE
Uncontrolled CPU, catatonic behavior

### ISSUE THREAD

**Issue by tripleee** [Charcoal-SE/PulseMonitor#9]
Over the last week or so, PulseMonitor has lost touch with the world and consumed insane amounts of CPU inside its container. On two of those occasions so far, I had to reboot the host on which it was running (though kernel updates and suspicions of an AWS problem also played into that decision).

Just now, it was dead again, and `docker stats 7595af52e07b` revealed some 500% CPU consumption. Outside of the Docker image, the symptom was `python3` steadily consuming 99.9% of CPU at a load slightly above 1.

**Comment by double-fault** [comment]
This was caused due to command threads not terminating; use the `running commands` command to see if this is happening. I can't find any specific way to repro this, so I'm guessing it is not an issue with Botpy, but if you see something causing this, please inform me!

**Comment by tripleee** [comment]
Closing as norepro because it has been reasonably stable over the last several months.
